### ISSUE TITLE
Not working with merge commits?

### ISSUE THREAD

**Issue by Snuffsis** [loopwerk/tag-changelog#11]
I like to make a new branch when I start working on a fix or a feature.   
And I have the habit of creating Merge Commits when merging a pull request into the active branch when I am done.

But it doesn't seem like it picks up all the commit history of the branch when doing it like this?
I seem to recall that it worked previously.

All my commits follow conventional commit format (except for the merge commit). 
![bild](https://user-images.githubusercontent.com/8822958/229542852-e387ae05-5446-4883-89d9-9b28f05968c9.png)

And then this is what the changelog ends up as:
![bild](https://user-images.githubusercontent.com/8822958/229543023-31b98022-52dd-450c-9c23-be063f7ca56c.png)

**Comment by kevinrenskers** [comment]
> I seem to recall that it worked previously.

Can you recall when it still worked as you expected, and when it no longer did? Can you try old versions of tag-changelog to pin it down?

**Comment by Snuffsis** [comment]
I have another project that is using v1 where it was working back in january this year, but i did try v1 for this and i was getting the same issue.

Here is the release page (edit: i cropped this poorly, it als has a bugfixes section for the single fix: item):
![bild](https://user-images.githubusercontent.com/8822958/229691185-af758fae-a0a3-4f60-8c50-378f957e3549.png)

and here is the commit history (ignore the latest commit) where the commits before each pullrequest was done for each respective branch:
![bild](https://user-images.githubusercontent.com/8822958/229691411-bad6b841-0d5b-4a0c-8a1f-1a378d3bd524.png)

**Comment by Snuffsis** [comment]
I found the issue.
The version number i supplied wasn't a valid semver numbering. I wanted it to be v0.1-beta since the last 0 wouldn't necessary, but that isn't valid. When I changed it at pushed it again as v0.1.0-beta it worked.

**Comment by kevinrenskers** [comment]
I'm glad you found the issue, thanks for letting me know!
