### ISSUE TITLE
Tags from Octokit are sorted alphabetically, possibly causing problems for this action

### ISSUE THREAD

**Issue by ldicarlo** [loopwerk/tag-changelog#12]
Hello, and thank you for this github action. 
I am not sure, but this line https://github.com/loopwerk/tag-changelog/blob/1b03d1a537bb49a99ca80ba8f5448be1ea4a0497/src/index.js#L43
Seems to take the last 2 tags but not among the 10 last tags ? 
When I run locally in a repository ( using `gh api /repos/<owner>/<repo>/tags | jq`), I get 10 tags but not the last ones. 

In one of our projects we have always the same changlelog generated. 

I don't have a large set of debugging available, so I am sorry by advance if this is an error. 
Thank you

**Comment by kevinrenskers** [comment]
This repo itself has 16 tags and the releases seem to work fine: https://github.com/loopwerk/tag-changelog/releases. The last one is exactly what I expect it to be.

**Comment by ldicarlo** [comment]
The examples I have are on a private repository, but the API returns tags beginnings by letters before the ones beginning by version number.

**Comment by kevinrenskers** [comment]
Then you're probably in the best position to create a PR with a fix?

**Comment by ldicarlo** [comment]
In your case for example, I suspecct that if you have 10 tags named "yXXX", they will always be shown before your tags "vXXX".
so you will never be able to produce the changelog

**Comment by ldicarlo** [comment]
> Then you're probably in the best position to create a PR with a fix?

The stupidest fix I can think about is to increase the page size, but this obviously not a good solution

**Comment by ldicarlo** [comment]
The release API is in reversed chronological order (last first) . What do you think about that? There is a tag attribute inside, but we'd need to think of what to do if there is no previous release. 

https://octokit.github.io/rest.js/v19#repos-get-latest-release <- I can try to do a PR using that if you want

(sorry for all the edits)

**Comment by kevinrenskers** [comment]
But the release most likely doesn't exist yet.. all you have is a pushed tag, which you use to create a release and a changelog. You can't use releases as the basis for this action.

**Comment by ldicarlo** [comment]
Yes but it's the same as the first tag ever in the repository right?

**Comment by kevinrenskers** [comment]
No. Something needs to trigger the workflow, that kicks this action. The creation of a release is a bad trigger, since you most likely want to create a release in the workflow that uses this action.

**Comment by ldicarlo** [comment]
no I meant, on a new tag you would compare the tag with the tag of the latest release, instead of checking the last tag

**Comment by kevinrenskers** [comment]
I've created a quick test script, and for me this API does return the latest tags.

```
const { Octokit } = require("@octokit/rest");

const octokit = new Octokit({
  auth: "my_auth_token", // https://github.com/settings/tokens/new
  userAgent: "test v1.2.3",
});

octokit.rest.repos
  .listTags({
    owner: "loopwerk",
    repo: "tag-changelog",
    per_page: 2,
  })
  .then(data => {
    console.log(data);
  });
```

This returns tags `v1.1.0` and `v1.0.5` as expected.

If this doesn't work for you and your repo, then maybe the tags were created in the wrong order? I don't know what to tell you, but at this moment there doesn't seem to be a bug that needs fixing. I am using this actions in multiple of my own repos  (some with `vx.x.x` tags and some just with `x.x.x` tags) and never ran into problems with it generating the wrong changelog.

**Comment by kevinrenskers** [comment]
> no I meant, on a new tag you would compare the tag with the tag of the latest release, instead of checking the last tag

Releases don't have to be based on tags.

**Comment by ldicarlo** [comment]
I will not insist more than this, I understand what you say. 

I will just be more pecise about the behaviour:
- change the page size to 1 (or create 10 tags beginning with `y` in step 2)
- create a tag `v1.2`
- create a tag `ySomeName`
- create a tag `v1.3`


Now I think that you will never have another release because the `yXXX` tags will come before in the list of 10 (or 1)  and do not match the regex.

**Comment by kevinrenskers** [comment]
Ok, I've reproduced the problem. The tags that you get back are indeed sorted alphabetically (reversed) rather than by creation date, so if you mix and match different kinds of tags.. yeah it's not going to work.

```
[
  {
    name: 'y6',
    zipball_url: 'https://api.github.com/repos/kevinrenskers/tag-test/zipball/refs/tags/y6',
    tarball_url: 'https://api.github.com/repos/kevinrenskers/tag-test/tarball/refs/tags/y6',
    commit: {
      sha: '1f36040ffebb5504808ea1ca02cd5d43c248fab0',
      url: 'https://api.github.com/repos/kevinrenskers/tag-test/commits/1f36040ffebb5504808ea1ca02cd5d43c248fab0'
    },
    node_id: 'REF_kwDOJawcDKxyZWZzL3RhZ3MveTY'
  },
  {
    name: 'y3',
    zipball_url: 'https://api.github.com/repos/kevinrenskers/tag-test/zipball/refs/tags/y3',
    tarball_url: 'https://api.github.com/repos/kevinrenskers/tag-test/tarball/refs/tags/y3',
    commit: {
      sha: '1fa7f0fe82a9d8cba2a8f8694a50a6a28cab08b7',
      url: 'https://api.github.com/repos/kevinrenskers/tag-test/commits/1fa7f0fe82a9d8cba2a8f8694a50a6a28cab08b7'
    },
    node_id: 'REF_kwDOJawcDKxyZWZzL3RhZ3MveTM'
  },
  {
    name: 'y2',
    zipball_url: 'https://api.github.com/repos/kevinrenskers/tag-test/zipball/refs/tags/y2',
    tarball_url: 'https://api.github.com/repos/kevinrenskers/tag-test/tarball/refs/tags/y2',
    commit: {
      sha: 'c96bf11d843f8cd1100f78a08f998bc21a48a23f',
      url: 'https://api.github.com/repos/kevinrenskers/tag-test/commits/c96bf11d843f8cd1100f78a08f998bc21a48a23f'
    },
    node_id: 'REF_kwDOJawcDKxyZWZzL3RhZ3MveTI'
  },
  {
    name: 'y1',
    zipball_url: 'https://api.github.com/repos/kevinrenskers/tag-test/zipball/refs/tags/y1',
    tarball_url: 'https://api.github.com/repos/kevinrenskers/tag-test/tarball/refs/tags/y1',
    commit: {
      sha: 'ea164f0a4dbeb5ae260a9459e8a88c6a8a5c2040',
      url: 'https://api.github.com/repos/kevinrenskers/tag-test/commits/ea164f0a4dbeb5ae260a9459e8a88c6a8a5c2040'
    },
    node_id: 'REF_kwDOJawcDKxyZWZzL3RhZ3MveTE'
  },
  {
    name: 'v7',
    zipball_url: 'https://api.github.com/repos/kevinrenskers/tag-test/zipball/refs/tags/v7',
    tarball_url: 'https://api.github.com/repos/kevinrenskers/tag-test/tarball/refs/tags/v7',
    commit: {
      sha: '8f88d134746a3bc95cac3b72dad1b6c7c5aae6cb',
      url: 'https://api.github.com/repos/kevinrenskers/tag-test/commits/8f88d134746a3bc95cac3b72dad1b6c7c5aae6cb'
    },
    node_id: 'REF_kwDOJawcDKxyZWZzL3RhZ3Mvdjc'
  },
  {
    name: 'v4',
    zipball_url: 'https://api.github.com/repos/kevinrenskers/tag-test/zipball/refs/tags/v4',
    tarball_url: 'https://api.github.com/repos/kevinrenskers/tag-test/tarball/refs/tags/v4',
    commit: {
      sha: 'f433e1648a60d44d3892ddc854ca4a92c9474b57',
      url: 'https://api.github.com/repos/kevinrenskers/tag-test/commits/f433e1648a60d44d3892ddc854ca4a92c9474b57'
    },
    node_id: 'REF_kwDOJawcDKxyZWZzL3RhZ3MvdjQ'
  }
]
```

I don't think there is a 100% fool-proof way to fix this problem with the GitHub API that we have. I guess this action simply doesn't work if you use different kinds of tags in one repo.

Your suggestion to use the previous release and use that tag is not foolproof either, as not all releases have a tag. Or maybe you use this action to only create a changelog file, but no releases. We simply can't assume there'll always be a release!

I think the only option is to fetch ALL tags and sort them ourselves using semver logic, but we can only request a maximum of 100 tags, and we don't know how many pages of results there will be, so we have to keep fetching pages until nothing is returned anymore. 

It's doable, but to be honest not something I want to spend my free time on as I am not running into this problem. I'd be happy to merge a well-written PR with tests for the logic though. Sorry I don't have better news.

**Comment by ldicarlo** [comment]
Actually no, it's a good news for me that there is really a problem and I just did not disturb you for nothing.

I'll give some thoughts to that. Right now I am thinking the best way to fix that would be to crawl all the tag pages to keep only valid tags.

Thank you anyway for taking the time to answer

**Comment by kevinrenskers** [comment]
Yeah once you fetched all the tags, you can easily filter out and sort only the valid tags using the existing logic: https://github.com/loopwerk/tag-changelog/blob/main/src/index.js#L49-L54.
