### ISSUE TITLE
failed to read commits between previous and new tag

### ISSUE THREAD

**Issue by gagan-multani** [loopwerk/tag-changelog#16]
I am using semantic tags such as 1.2.0, 1.2.1, 1.2.2, or v1.2.0, v1.2.1, v1.2.2 and still getting empty body.

**Comment by kevinrenskers** [comment]
That's not enough information for me. Please post your workflow, link to your repo, have a reproducible example, something like that.

**Comment by gagan-multani** [comment]
I want to rephrase the problem "Change-log action failed to read commits between previous and new tag, it is being stuck on commits between  " 2.3.22-partner and 2.3.22-rc " tags

![Screenshot from 2023-12-18 15-03-05](https://github.com/loopwerk/tag-changelog/assets/151516938/df21f411-917a-4d15-bff3-8e768a970363)
![Screenshot from 2023-12-18 15-03-55](https://github.com/loopwerk/tag-changelog/assets/151516938/859b3fd5-c411-4210-885e-3ff229d2c1f6)
![Screenshot from 2023-12-18 15-04-20](https://github.com/loopwerk/tag-changelog/assets/151516938/7c901a9f-9613-43a0-9e81-2c63e54e4491)

**Comment by kevinrenskers** [comment]
Tags like 2.3.22-partner, 2.3.22-rc and 2.3.22-dev seem unlikely to me to work, it’s not something I’ve tested myself, it’s not something I need to work for myself either. As such it’s not something I’m going to put time into, sorry.

I welcome you to send a PR that adds missing support.

**Comment by kevinrenskers** [comment]
It's been almost a year with no further replies, so I am closing this.
