### ISSUE TITLE
If I am submitting a tag for the first time, the code logic will throw an exception

### ISSUE THREAD

**Issue by ChoGathK** [loopwerk/tag-changelog#4]
Is it possible to be compatible with the first two submissions?

**your code**

```js 
  // Find the two most recent tags
  const { data: tags } = await octokit.repos.listTags({
    owner,
    repo,
    per_page: 10,
  });

  const validSortedTags = tags
    .filter((t) => compareVersions.validate(t.name))
    .sort((a, b) => {
      return compareVersions(a.name, b.name);
    })
    .reverse();

  if (validSortedTags.length < 2) {
    setFailed("Couldn't find previous tag");
    return;
  }
```

**Comment by ChoGathK** [comment]
Sorry, I didn't see the `Roadmap` in your document

**Comment by kevinrenskers** [comment]
Glad you found the roadmap! If this is something you need, and something you’d want to take a look at, it would be great if you could submit a PR that fixes this limitation.

**Comment by ChoGathK** [comment]
I will 😄

**Comment by ChoGathK** [comment]
@kevinrenskers , how are you today? This actions app was a source of inspiration for me, and you might find it useful as well：

https://github.com/marketplace/actions/release-changelog-builder#customization-%EF%B8%8F

**Comment by ChoGathK** [comment]
After some time of testing, I decided to use the commands that come with github, thanks for your application, it really helped me a lot during this time.

```
gh release create --generate-notes
```

Like this: https://github.com/vodyani/workflows/blob/57439853471f84cb971c449b49649ccdfa487a26/.github/workflows/publish-release.yml#L28

**Comment by kevinrenskers** [comment]
Interesting!
