### ISSUE TITLE
how to get the release notes and send it to an email

### ISSUE THREAD

**Issue by lisleyanne20** [loopwerk/tag-changelog#6]
Hi,

I am using this workflow and it is working fine. I would like to get the ${{ steps.changelog.outputs.changes }} and send it via email. But I am not getting anything. I am using this code to get the changes:
- name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
        # Required mail server address:
        server_address: 
        # Required mail server port:
        server_port: 
        # Optional (recommended): mail server username:
        username: 
        # Optional (recommended) mail server password:
        password: 
        # Required mail subject:
        subject: 
        # Required recipients' addresses:
        to: 
        # Required sender full name (address can be skipped):
        from: 
        # Optional whether this connection use TLS (default is true if server_port is 465)
        secure: 
        # Optional plain body:
        body:  ${{ steps.changelog.outputs.changes }}
        # Optional unsigned/invalid certificates allowance:
        ignore_cert: 
        # Optional converting Markdown to HTML (set content_type to text/html too):
        convert_markdown: 
        # Optional priority: 'high', 'normal' (default) or 'low'
   
I hope you can assist me with this one.
Thank you so much.
- Lisley

**Comment by kevinrenskers** [comment]
I'm afraid I can't help with your email workflow. But one question: did you fill in all those required values?

You might need to seek help with the email action if you're not getting any email.

**Comment by lisleyanne20** [comment]
> I'm afraid I can't help with your email workflow. But one question: did you fill in all those required values?
> 
> You might need to seek help with the email action if you're not getting any email.

Yup all the required values is provided. Will change the question then, since the step below is working on another repo:
  - name: Create changelog text
      id: changelog
      uses: loopwerk/tag-changelog@v1
      with:
        token: ${{secrets.CHANGES_TOKEN}}
        config_file: .github/tag-changelog-config.js
        exclude_types: other,doc,chore
But it does not work with another repo.
Here's the screenshot of the 2 repo:
<img width="426" alt="create changelog text not working" src="https://user-images.githubusercontent.com/42061656/184086597-0b3b2fd2-a2d5-49d5-b045-c4ad23c9da0b.png">
<img width="409" alt="create changelog text working" src="https://user-images.githubusercontent.com/42061656/184086608-f56ba99a-c038-4b57-990f-9718f3d83410.png">

It's weird that I am using the same workflow but the other one is perfectly working and the other is not.

**Comment by kevinrenskers** [comment]
I really can't help you debug your workflows, I'm sorry. 

One thing to keep in mind: this action only works if there are at least 2 tags found. So for the very first tag you add to the repo, nothing happens. Other than that, nothing comes to mind. This action works, how you slot it into a workflow is up to you. Good luck!

**Comment by lisleyanne20** [comment]
Thank you!
