### ISSUE TITLE
Stop using set-output

### ISSUE THREAD

**Issue by kevinrenskers** [loopwerk/tag-changelog#9]
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by kevinrenskers** [comment]
I think this will be a breaking change, forcing everyone to update their workflows. So, definitely a v2 release.

**Comment by houseful-chisel** [comment]
In my (limited) experience it's just changing how the outputs are **set** and doesn't affect anyone _reading_ the values.

For example, these are the full changes I made in one of my workflows:

```diff
-          echo "::set-output name=test-matrix::${matches}"
+          echo "test-matrix=${matches}" >> $GITHUB_OUTPUT
```

and

```diff
-          echo ::set-output name=tmp-dir::$tmpdir
+          echo "tmp-dir=${tmpdir}" >> $GITHUB_OUTPUT
```

**Comment by kevinrenskers** [comment]
So it turns out that tag-changelog doesn't have to do anything. It's one of the other actions that I use in my own [GitHub workflow](https://github.com/loopwerk/tag-changelog/blob/main/.github/workflows/run.yml) that causes the deprecation warning: `actions/create-release` uses an old version of `@actions/core`. And this action is deprecated anyway. 

So the fix here is to change the example workflow in the readme, and my own workflow, to not use `actions/create-release` anymore.
